[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
board_build.partitions = min_spiffs.csv
build_unflags = -std=gnu++11
build_flags =
  -std=gnu++17
  -D CORE_DEBUG_LEVEL=ARDUHAL_LOG_LEVEL_VERBOSE
  -D TAG='"Arduino"'
  -D USE_ESP_IDF_LOG
lib_deps =
  SensESP
  adafruit/Adafruit INA219 @ ^1.2.3
  milesburton/DallasTemperature @ ^3.11.0
  paulstoffregen/OneWire @ ^2.3.8

